M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date 15.05.2026 (пт) 15:03:49
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-15T15:03:49+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.300
%
G90
G05
T1
X22.11Y6.03
X27.89Y6.03
T2
X44.69Y6.0
X52.31Y6.0
T3
X44.3Y17.13
X55.7Y17.13
T4
X28.0Y54.0
X28.0Y16.0
X65.0Y54.0
X65.0Y16.0
M30
